Repository redBorder/cookbook-rb-manager, pull requests merged in 2023-12, with the labels that each got.

#89 add rb-selinux
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S

#92 add internal services for sync network
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#95 Release 1.6.2
  packaging/rpm/cookbook-rb-manager.spec
  resources/metadata.rb
Labels: size/XS, kind/documentation

#94 Add kafka_hosts for http2k
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#96 Add logstatter in cgroup and systemd & configure service for chef
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#98 Release 1.6.4
  packaging/rpm/cookbook-rb-manager.spec
  resources/metadata.rb
Labels: size/XS, kind/documentation

#99 added kafka hosts configuration to pmacct
  resources/recipes/configure.rb
Labels: bug, size/XS
