Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-04, with the labels that each got.

#111 pass all flow sensors to sflow pipeline
  resources/libraries/get_all_flow_sensors_info.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/S

#113 Release 1.7.2
  resources/metadata.rb
Labels: size/XS, kind/documentation

#114 Remove tier
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#115 Release 1.7.3
  CHANGELOG.md
Labels: size/XS

#116 Bump 1.7.3 cookbook
  resources/metadata.rb
Labels: kind/feature, size/XS

#119 add ipaddress sync for minio
  resources/recipes/configure.rb
Labels: size/XS

#121 Development
  .github/workflows/rpm.yml
  CHANGELOG.md
  resources/metadata.rb
Labels: kind/feature, size/M

#120 Release 1.7.4
  CHANGELOG.md
  resources/metadata.rb
Labels: size/XS, kind/documentation

#125 Release 1.7.5
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/prepare_system.rb
Labels: size/S, kind/documentation

#124 Druid realtime is not acting as a cluster because shardSpec partition is not correctly set
  resources/attributes/default.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/XS, kind/bug

#127 Release 1.7.6
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/S, kind/documentation, release
