Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-06, with the labels that each got.

#143 add temporary variables in node.run_state
  resources/libraries/get_pipelines.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: kind/feature, size/M

#144 Release 1.9.1
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/libraries/get_pipelines.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/motd.erb
Labels: size/L, kind/documentation

#146 Bugfix/#15141 fix geoip being removed
  resources/recipes/configure.rb
Labels: size/XS, kind/bug

#147 Release 1.9.2
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: bug, size/XS, kind/documentation, release

#148 Improvement/fix lint
  README.md
  resources/attributes/default.rb
  resources/libraries/get_all_flow_sensors_info.rb
  resources/libraries/get_cluster_info.rb
  resources/libraries/get_elasticache_nodes.rb
  resources/libraries/get_managers_all.rb
  resources/libraries/get_namespaces.rb
  resources/libraries/get_orgs.rb
  resources/libraries/get_pipelines.rb
  resources/libraries/get_sensors_all_info.rb
  resources/libraries/get_sensors_info.rb
  resources/libraries/harddisk_services.rb
  resources/libraries/in_hash.rb
  resources/libraries/manager_services.rb
  resources/libraries/managers_per_service.rb
  resources/libraries/memory_services.rb
  resources/libraries/node_services.rb
  resources/libraries/util.rb
  resources/recipes/configure.rb
  resources/recipes/configure_cron_tasks.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/sysconfig_chef-client.rb.erb
Labels: enhancement, kind/bug, lint, refactor

#151 Release 1.9.3
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/libraries/get_all_flow_sensors_info.rb
  resources/libraries/get_cluster_info.rb
  resources/libraries/get_elasticache_nodes.rb
  resources/libraries/get_managers_all.rb
  resources/libraries/get_namespaces.rb
  resources/libraries/get_orgs.rb
  resources/libraries/get_pipelines.rb
  resources/libraries/get_sensors_all_info.rb
  resources/libraries/get_sensors_info.rb
  resources/libraries/harddisk_services.rb
  resources/libraries/in_hash.rb
  resources/libraries/manager_services.rb
  resources/libraries/managers_per_service.rb
  resources/libraries/memory_services.rb
  resources/libraries/node_services.rb
  resources/libraries/util.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/configure_cron_tasks.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/sysconfig_chef-client.rb.erb
Labels: kind/documentation

#145 Configure minio nodes and load balancer
  resources/attributes/default.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/minio.erb
Labels: size/M

#152 release 2.0.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/minio.erb
Labels: kind/documentation, size/M

#150 Configure webui nginx load balancer
  resources/attributes/default.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: kind/feature, size/S

#153 Release 2.0.1
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/S, kind/documentation

#149 add keepalived and balanced services
  resources/attributes/default.rb
  resources/libraries/get_managers_all.rb
  resources/libraries/get_virtual_ip_info.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/L, kind/documentation

#155 Release 2.1.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/get_managers_all.rb
  resources/libraries/get_virtual_ip_info.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/L, kind/documentation

#156 Bugfix/17318 check logstash pipeline is active
  resources/libraries/get_monitor_configuration.rb
  resources/libraries/get_monitor_in_proxy.rb
  resources/libraries/get_pipelines.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/S, kind/bug, size/M

#157 Add clamav to redborder
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#159 change 'or' to 'and' and add same check to mobility pipeline
  resources/libraries/get_pipelines.rb
Labels: size/XS

#161 Add memcached hosts to the webui
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#160 Release 2.2.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/get_monitor_configuration.rb
  resources/libraries/get_monitor_in_proxy.rb
  resources/libraries/get_pipelines.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/L, kind/documentation

#166 Hotfix: get pipeline fix if values are nil
  resources/libraries/get_pipelines.rb
Labels: size/S, kind/bug
