Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-07, with the labels that each got.

#163 Feature/#17820 add intrusion pipeline
  resources/libraries/get_pipelines.rb
Labels: kind/feature, size/XS

#168 Release 2.3.0
  CHANGELOG.md
  resources/libraries/get_pipelines.rb
  resources/metadata.rb
Labels: kind/feature, size/XS

#162 #17853 Minio cannot stop on custom node
  resources/recipes/configure.rb
Labels: size/XS, kind/bug

#171 Feature/incident response
  resources/attributes/default.rb
  resources/libraries/get_api_auth_token.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/L, kind/feature

#169 Release 2.4.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/get_api_auth_token.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/L, kind/documentation

#173 Feature #17728: Integration with SAML
  resources/attributes/default.rb
Labels: kind/feature, size/XS

#175 Release 2.5.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
Labels: kind/documentation
