Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-08, with the labels that each got.

#170 Bug/#17959 add memcached hosts to druid common propiertes
  resources/recipes/prepare_system.rb
Labels: kind/feature, size/M

#177 Feature/#18106 install llamafile as service
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S

#186 Release 2.6.2
  CHANGELOG.md
  resources/metadata.rb
  resources/templates/default/redborder-manager.erb
Labels: size/XS, kind/bug

#174 Add chronyd cookbook
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/S

#188 Bugfix #18334 Add sync address to redborder-ai
  resources/recipes/configure.rb
Labels: bug

#189 Release 2.7.1
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/XS, kind/bug
