Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-02, with the labels that each got.

#107 Improvement/16142 motd
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/motd.erb
Labels: kind/feature, size/M

#108 Add rb aioutliers back to redborder ng (python version)
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: feature, kind/feature, size/M

#109 Modify version
  resources/metadata.rb
Labels: size/XS, kind/documentation
