Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-05, with the labels that each got.

#126 imported logstash template from centos6
  resources/libraries/get_pipelines.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: kind/bug, size/M

#128 Release 1.7.7
  CHANGELOG.md
  resources/libraries/get_pipelines.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: kind/documentation, size/M

#130 fix_logstash_crash
  resources/libraries/get_pipelines.rb
Labels: size/XS, kind/bug

#131 Release 1.7.8
  CHANGELOG.md
  resources/libraries/get_pipelines.rb
  resources/metadata.rb
Labels: size/XS, kind/documentation

#132 Bugfix/17236 logstash enabled without pipelines
  resources/recipes/prepare_system.rb
Labels: kind/feature, size/XS

#133 Revert "Bugfix/17236 logstash enabled without pipelines"
  resources/recipes/prepare_system.rb
Labels: size/XS, kind/bug

#129 excluding chef-client not to be a memservice
  resources/attributes/default.rb
  resources/libraries/memory_services.rb
  resources/recipes/prepare_system.rb
Labels: kind/bug, size/M

#134 Release 1.7.9
  CHANGELOG.md
  Makefile
  resources/attributes/default.rb
  resources/libraries/memory_services.rb
  resources/metadata.rb
  resources/recipes/prepare_system.rb
Labels: kind/documentation, size/M

#135 Stop logstash when there are no pipelines
  resources/recipes/configure.rb
Labels: bug, size/S, kind/bug

#137 Release 1.7.10
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/documentation, size/M

#136 Feature/#16519 integrate rb ale
  resources/attributes/default.rb
  resources/templates/default/redborder-manager.erb
Labels: kind/feature, size/S

#139 add postfix service
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#138 Release 1.8.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation

#140 Add configure common cookbook call
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: feature, kind/feature, size/XS

#141 Release 1.9.0
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation

#142 Add full kernel release info in motd
  resources/templates/default/motd.erb
Labels: size/XS, kind/documentation
