Repository redBorder/cookbook-rb-manager, pull requests merged in 2024-01, with the labels that each got.

#93 Improvement/#15954 configure journalctl
  resources/recipes/configure.rb
  resources/recipes/configure_cron_tasks.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/templates/default/systemd-journald_journald.conf.erb
Labels: kind/feature, size/M

#101 Release/1.6.6
  packaging/rpm/cookbook-rb-manager.spec
  resources/metadata.rb
Labels: size/XS, kind/documentation

#100 adding rb-arubacentral
  resources/attributes/default.rb
  resources/libraries/get_sensors_all_info.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/S

#103 Release 1.6.7
  packaging/rpm/cookbook-rb-manager.spec
Labels: size/XS, kind/documentation

#102 PR 102 - Add positiblity to custom set Storage value of journald configuration
  resources/recipes/configure_journald.rb
  resources/templates/default/systemd-journald_journald.conf.erb
Labels: kind/feature, size/S

#104 Release 1.6.8
  packaging/rpm/cookbook-rb-manager.spec
Labels: size/XS, kind/documentation

#105 Fix .spec file
  packaging/rpm/cookbook-rb-manager.spec
Labels: size/XS, kind/bug

#106 Update metadata.rb
  resources/metadata.rb
Labels: size/XS, kind/documentation
