Repository redBorder/cookbook-rb-manager, pull requests merged in 2025-09, with the labels that each got.

#344 Feature/#22472 Replace title/description generation with redborder-agents instead of rb-llm
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: enhancement

#343 Feature/#22453 create s3 malware bucket
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#341 Feature #22340: Bring back malware pipeline
  resources/libraries/get_pipelines.rb
  resources/recipes/configure.rb
Labels: feature, kind/feature, size/XS
