Repository redBorder/cookbook-rb-manager, pull requests merged in 2025-06, with the labels that each got.

#306 Release 5.3.2
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure_cron_tasks.rb
Labels: release

#307 Bugfix/#21781 Generate key .rsa with chef in ~/.ssh/ and use it in rbcli instead of using the rails one
  resources/recipes/configure.rb
  resources/templates/default/rsa_cert.pem.erb
Labels: bug

#303 Bugfix #21548 Syslog port 514 is open for everybody in public
  resources/recipes/configure.rb
Labels: bug, size/XS, kind/bug

#315 Bugfix/#21851 When enabling nginx in a custom node (cluster), it always fails
  resources/recipes/configure.rb
Labels: bug

#316 Release 5.4.5
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/bug, release
