Repository redBorder/cookbook-rb-manager, pull requests merged in 2025-07, with the labels that each got.

#323 Release 5.4.7
  CHANGELOG.md
  resources/libraries/get_indexer_tasks.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: bug, size/M, release

#324 Improvement/#19203 Refactor S3 Variables Passing in Cookbooks
  resources/recipes/configure.rb
Labels: enhancement

#209 Feature/#18850 Add internal virtual ips
  resources/attributes/default.rb
  resources/libraries/get_virtual_ip_info.rb
  resources/libraries/set_internal_vip.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: feature

#331 Release 5.5.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/get_virtual_ip_info.rb
  resources/libraries/set_internal_vip.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: enhancement, size/M, release, refactor

#328 Improvement/#22172 Replace Memcached with a Key-Listable Service (e.g., Redis) for Incident Creation
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: enhancement
